[tool.poetry]
name = "gpt-scorer"
version = "0.1.0"
description = ""
authors = ["Jarki <yaroslav.ivashko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.55.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
